### ISSUE TITLE
Problems with the way PoWriter "escapes" some characters

### ISSUE THREAD

**Issue by adlq** [zanata/jgettext#1]
I feel like the writeString method from PoWriter appends unnecessary blackslashes onto the PO message it is writing. I can't find the fact that double backslashes are needed to escape special characters anywhere in the [Gettext manual](http://www.gnu.org/software/gettext/manual/html_node/Preparing-Strings.html).

For instance, instead of having:

```
msgid "Hello \"World\""
msgstr ""
```

writeString outputs:

```
msgid "Hello \\\"World\\\""
msgstr ""
```

Which, as far as I know, completely changes my string.

Could someone explain to me the "currentLine.append('\');" calls in the writeString method?

**Comment by seanf** [comment]
Very sorry @adlq, I didn't see your bug report until now. I didn't realise GitHub Issues was turned on for this repository. I'm not sure if you still have any interest in JGettext, but I'll try to answer anyway.

All of the instances of: 

    currentLine.append('\\');

in `PoWriter.writeString` are there to escape special characters like newline, backslash and quotes.

The gettext manual doesn't go into complete detail, but it does show quotes `"` being escaped as `\%"`, and if `\` is an escape character, there needs to be a way of escaping it. (So of the three backslashes in `msgid "Hello \\\"World\\\""`, two represent a literal backslash, the other escapes a quote character.)

You didn't say exactly what string was being written, but if the string being written is `Hello \"World\"` (with actual backslashes and quote characters for some strange reason), I believe it _should_ appear in a gettext file as `msgid "Hello \\\"World\\\""`. 

On the other hand, if the string was actually `Hello "World"` (with quotes but no backslashes), that would be a bug, but I would be surprised that such a simple problem hadn't shown up anywhere else, because Zanata has used JGettext heavily for years. However, you might be using a different part of JGettext from what Zanata uses, so it's not impossible.

It looks to me like the string `Hello "World"` may have been encoded twice somehow. The first encoding would have introduced the backslash when it escaped the quote, and the second encoding escaped the backslash as well as the quote.
